"""owner sales_o default True

Revision ID: adf2aa1f46b7
Revises: f2d26c7f58fb
Create Date: 2024-11-28 23:13:53.076200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adf2aa1f46b7'
down_revision = 'f2d26c7f58fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.alter_column('sales_o',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owners', schema=None) as batch_op:
        batch_op.alter_column('sales_o',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
