version: '2'

services:
  db:
    image: mysql:8
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql


  web:
    build: ./app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./tests:/tests
    environment:
      - FLASK_ENV=development  
    command: flask run --host=0.0.0.0 --reload
    env_file: .env
    depends_on:
      - db

volumes:
  db_data:

